[2025-04-03 11:49:45 -0400] [1300555] [INFO] Starting gunicorn 23.0.0
[2025-04-03 11:49:45 -0400] [1300555] [INFO] Listening at: http://0.0.0.0:8000 (1300555)
[2025-04-03 11:49:45 -0400] [1300555] [INFO] Using worker: sync
[2025-04-03 11:49:45 -0400] [1300556] [INFO] Booting worker with pid: 1300556
[2025-04-03 11:49:45 -0400] [1300557] [INFO] Booting worker with pid: 1300557
[2025-04-03 11:49:45 -0400] [1300558] [INFO] Booting worker with pid: 1300558
[2025-04-03 11:49:45 -0400] [1300559] [INFO] Booting worker with pid: 1300559
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
Invalid HTTP_HOST header: 'wiki-annotation.umiacs.umd.edu'. You may need to add 'wiki-annotation.umiacs.umd.edu' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wiki-annotation.umiacs.umd.edu'. You may need to add 'wiki-annotation.umiacs.umd.edu' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'wiki-annotation.umiacs.umd.edu'. You may need to add 'wiki-annotation.umiacs.umd.edu' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/srv/www/wiki-annotation/Appraise-wiki/.venv/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'wiki-annotation.umiacs.umd.edu'. You may need to add 'wiki-annotation.umiacs.umd.edu' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[2025-04-03 11:52:12 -0400] [1300555] [INFO] Handling signal: term
[2025-04-03 15:52:12 +0000] [1300556] [INFO] Worker exiting (pid: 1300556)
[2025-04-03 15:52:12 +0000] [1300557] [INFO] Worker exiting (pid: 1300557)
[2025-04-03 15:52:12 +0000] [1300558] [INFO] Worker exiting (pid: 1300558)
[2025-04-03 15:52:12 +0000] [1300559] [INFO] Worker exiting (pid: 1300559)
[2025-04-03 11:52:13 -0400] [1300555] [INFO] Shutting down: Master
[2025-04-03 11:54:52 -0400] [1300750] [INFO] Starting gunicorn 23.0.0
[2025-04-03 11:54:52 -0400] [1300750] [INFO] Listening at: http://0.0.0.0:8000 (1300750)
[2025-04-03 11:54:52 -0400] [1300750] [INFO] Using worker: sync
[2025-04-03 11:54:52 -0400] [1300751] [INFO] Booting worker with pid: 1300751
[2025-04-03 11:54:52 -0400] [1300752] [INFO] Booting worker with pid: 1300752
[2025-04-03 11:54:52 -0400] [1300753] [INFO] Booting worker with pid: 1300753
[2025-04-03 11:54:52 -0400] [1300754] [INFO] Booting worker with pid: 1300754
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
/srv/www/wiki-annotation/Appraise-wiki/Appraise/settings.py:34: UserWarning: Using the default SECRET_KEY value! Set and export APPRAISE_SECRET_KEY envvar instead
  warnings.warn(
